type Player {
  userDocId: String
  username: String
  avatar: String
}

type BetRedis {
  docId: String
  intervals: [Int]
  amountBet: Int
  createdAt: String
  gameId: String
  userInfo: Player
}

type TicketDrawn {
  ticket: Int
  hash: String
}

type GameData {
  docId: String
  bets: [BetRedis]
  type: String
  winningBetRef: BetRedis
  ticketDrawn: TicketDrawn
  prizePool: Int
  status: String
  createdAt: String
  startedAt: String
  updatedAt: String
  finishedAt: String
  jackpotDuration: Int
  jackpotAnimationDuration: Int
}

type Game {
  success: Boolean!
  message: String!
  data: GameData!
}

type GameHistory {
  success: Boolean!
  message: String!
  data: [GameData]
}

type Query {
  getJackpot: Game!
  getLastJackpots: GameHistory!
}

type Subscription {
  getLiveJackpot: Game!
  getLiveLastJackpots: GameHistory!
}
